name: Deploy Flask App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
      
      - name: Initialize database
        run: |
          python init_all_data.py
      
      - name: Create admin user
        run: |
          python create_admin.py
      
      - name: Build static files
        run: |
          # Create a simple index.html for GitHub Pages
          mkdir -p _site
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ru">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Semey-KM Factory Management System</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  .container {
                      background: white;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  .logo {
                      text-align: center;
                      margin-bottom: 30px;
                  }
                  .logo h1 {
                      color: #2c3e50;
                      margin: 0;
                  }
                  .info {
                      background: #e8f4fd;
                      padding: 20px;
                      border-radius: 5px;
                      margin: 20px 0;
                  }
                  .warning {
                      background: #fff3cd;
                      border: 1px solid #ffeaa7;
                      padding: 15px;
                      border-radius: 5px;
                      margin: 20px 0;
                  }
                  .btn {
                      display: inline-block;
                      padding: 12px 24px;
                      background: #007bff;
                      color: white;
                      text-decoration: none;
                      border-radius: 5px;
                      margin: 10px 5px;
                  }
                  .btn:hover {
                      background: #0056b3;
                  }
                  .features {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                      gap: 20px;
                      margin: 20px 0;
                  }
                  .feature {
                      background: #f8f9fa;
                      padding: 15px;
                      border-radius: 5px;
                      text-align: center;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="logo">
                      <h1>🏭 Semey-KM Factory Management System</h1>
                  </div>
                  
                  <div class="info">
                      <h3>📋 Система управления производством керамического завода</h3>
                      <p>Веб-приложение для отслеживания партий, материалов и оборудования с разграничением прав доступа.</p>
                  </div>
                  
                  <div class="warning">
                      <strong>⚠️ Внимание:</strong> Это Flask-приложение требует серверного окружения для работы. GitHub Pages поддерживает только статические сайты.
                  </div>
                  
                  <h3>🚀 Возможности системы:</h3>
                  <div class="features">
                      <div class="feature">
                          <strong>🔐 Авторизация</strong><br>
                          Разграничение прав доступа
                      </div>
                      <div class="feature">
                          <strong>📦 Управление партиями</strong><br>
                          Отслеживание продукции
                      </div>
                      <div class="feature">
                          <strong>🧱 Учёт материалов</strong><br>
                          Контроль расхода
                      </div>
                      <div class="feature">
                          <strong>🏭 Мониторинг</strong><br>
                          Состояние оборудования
                      </div>
                  </div>
                  
                  <h3>📁 Репозиторий и документация:</h3>
                  <a href="https://github.com/Anubizze/semey-km" class="btn">📂 GitHub Repository</a>
                  <a href="https://github.com/Anubizze/semey-km/blob/main/README.md" class="btn">📖 README</a>
                  
                  <div class="info">
                      <h3>🛠️ Установка и запуск:</h3>
                      <ol>
                          <li>Клонируйте репозиторий</li>
                          <li>Создайте виртуальное окружение</li>
                          <li>Установите зависимости: <code>pip install -r requirements.txt</code></li>
                          <li>Инициализируйте БД: <code>python init_all_data.py</code></li>
                          <li>Запустите: <code>python app.py</code></li>
                      </ol>
                  </div>
                  
                  <div style="text-align: center; margin-top: 30px; color: #666;">
                      <p>🔧 Powered by Flask | 📊 CI/CD with GitHub Actions</p>
                  </div>
              </div>
          </body>
          </html>
          EOF
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
